// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_API_KEY',
      defaultValue: 'FIREBASE_WEB_API_KEY_PLACEHOLDER',
    ),
    appId: '1:100000000000:web:abcdef1234567890abcdef',
    messagingSenderId: '100000000000',
    projectId: 'johar-safety',
    authDomain: 'johar-safety.firebaseapp.com',
    storageBucket: 'johar-safety.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_ANDROID_API_KEY',
      defaultValue: 'FIREBASE_ANDROID_API_KEY_PLACEHOLDER',
    ),
    appId: '1:370462837536:android:effd4c9ac63cfb19672545',
    messagingSenderId: '370462837536',
    projectId: 'joharorg',
    storageBucket: 'joharorg.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_API_KEY',
      defaultValue: 'FIREBASE_IOS_API_KEY_PLACEHOLDER',
    ),
    appId: '1:370462837536:ios:853f968c5f5370ef672545',
    messagingSenderId: '370462837536',
    projectId: 'joharorg',
    storageBucket: 'joharorg.firebasestorage.app',
    iosClientId: '370462837536-e3gsndjg2ebqnv6ff0ebnh5od8a98dhn.apps.googleusercontent.com',
    iosBundleId: 'app.web.joharorg.johar',
  );
}
