import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'app.dart';
import 'core/services/locale_controller.dart';
import 'data/content/module_catalog.dart';
import 'data/local/local_store.dart';
import 'data/sync/sync_service.dart';
import 'features/refresher/refresher_store.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase init works without internet. If it fails (e.g. not configured
  // yet), the app still runs fully offline and simply never syncs.
  var firebaseReady = false;
  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    firebaseReady = true;
  } catch (e) {
    debugPrint('Firebase not available, running offline only: $e');
  }

  final store = await LocalStore.open();
  await RefresherStore.init();
  final localeController = await LocaleController.load();
  final sync = SyncService(store, firebaseEnabled: firebaseReady)..start();

  runApp(JoharApp(
    store: store,
    sync: sync,
    localeController: localeController,
    content: ContentRepository(),
  ));
}
